use db_app;
/* RELLENANDO TABLAS CON DATOS FIJOS */
# from tbl_tipos_usuarios;
insert into tbl_tipos_usuarios(id, tipo_usuario)
values
    -- nombre_tipo
    (null, 'Paciente'),
    (null, 'Doctor'),
    (null, 'Farmacia'),
    (null, 'Isp');

-- sexo
insert into tbl_sexo(id, sexo)
values (null, 'Femenino'),
       (null, 'Masculino'),
       (null, 'otro');

insert into tbl_provincias(id, provincia)
values (null, 'Chacabuco'),
       (null, 'Cordillera'),
       (null, 'Maipo'),
       (null, 'Milipilla'),
       (null, 'Santiago'),
       (null, 'Talagante');

insert into tbl_comunas(id, comuna, id_provincia)
values (null, 'colina', 1),
       (null, 'Lampa', 1),
       (null, 'Til Til', 1),
       (null, 'Pirque', 2),
       (null, 'Puente Alto', 2),
       (null, 'San Jose de Maipo', 2),
       (null, 'Buin', 3),
       (null, 'Calera de Tango', 3),
       (null, 'Paine', 3),
       (null, 'San Bernardo', 4),
       (null, 'Alhué', 4),
       (null, 'Curacaví', 4),
       (null, 'María Pinto', 4),
       (null, 'Milipilla', 4),
       (null, 'San Pedro', 4),
       (null, 'Cerrillo', 5),
       (null, 'Cerro Navia', 5),
       (null, 'Conchalí', 5),
       (null, 'El Bosque', 5),
       (null, 'Estación Central', 5),
       (null, 'Huechuraba', 5),
       (null, 'Independencia', 5),
       (null, 'La Cisterna', 5),
       (null, 'La Granja', 5),
       (null, 'La Florida', 5),
       (null, 'La Pintana', 5),
       (null, 'La Reina', 5),
       (null, 'Las Condes', 5),
       (null, 'Lo Barnechea', 5),
       (null, 'Lo Espejo', 5),
       (null, 'Lo Prado', 5),
       (null, 'Macul', 5),
       (null, 'Maipú', 5),
       (null, 'Ñuñoa', 5),
       (null, 'Pedro Aguirre Cerda', 5),
       (null, 'Peñalolén', 5),
       (null, 'Providencia', 5),
       (null, 'Pudahuel', 5),
       (null, 'Quinta Normal', 5),
       (null, 'Recoleta', 5),
       (null, 'Renca', 5),
       (null, 'San Miguel', 5),
       (null, 'San Joaquín', 5),
       (null, 'San Ramón', 5),
       (null, 'Santiago', 5),
       (null, 'Vitacura', 5),
       (null, 'El Monte', 6),
       (null, 'Isla de Maipo', 6),
       (null, 'Peñaflor', 6),
       (null, 'Talagante', 6);


insert into tbl_establecimientos (id, rut_establecimiento, nombre_establecimiento, direccion_establecimiento, id_comuna,
                                  fono_establecimiento, email_establecimiento, id_imagen, created_at, updated_at)
values (null, '1923', 'Farmacias Cruz Verde', ' Eliodoro Yañez 1281, Santiago, Providencia, Región Metropolitana', 37,
        '800 802 800', 'cruzverde@cruzverde.cl', null, curdate(), curdate()),
       (null, 'sds', 'Farmacia Online Pharol', ' San Pablo 3136, Santiago, Región Metropolitana', 40, '9 6158 8213',
        'Farmacia@cFarmacia.cl', null, curdate(), curdate()),
       (null, '45454', 'Farmacias Cruz Verde', ' Eliodoro Yañez 1281, Santiago, Providencia, Región Metropolitana', 37,
        '800 802 800', 'cruzverde@cruzverde.cl', null, curdate(), curdate()),
       (null, '19266453', 'Farmacias Ahumada', ' Nataniel Cox 620, Santiago, Región Metropolitana', 46, '(2) 3274 0568',
        'Ahumada@Ahumada.cl', null, curdate(), curdate()),
       (null, '1343434923', 'Centro Medico Torre Alameda | En el centro de Santiago',
        ' San Antonio 19, D 601 P 06, Santiago, Región Metropolitana', 37, '(2) 2633 0041',
        'centromedico@centromedico.cl', null, curdate(), curdate()),
       (null, '33444923', 'Centro Médico Vida Integra', ' Santiago, San Miguel, Región Metropolitana', 43,
        ' (2) 2731 2000', 'centromedico@centromedico.cl', null, curdate(), curdate()),
       (null, '444923', 'Centro Radiológico Los Héroes', 'Dieciocho 45, Santiago, Región Metropolitana', 46,
        '(2) 2840 4800', 'Centro@Centro.cl', null, curdate(), curdate()),
       (null, '4224923', 'Cenin Centros Médicos',
        'Av. Independencia 1222, Santiago, Independencia, Región Metropolitana', 22, '(2) 2737 1049', 'Cenin@Cenin.cl',
        null, curdate(), curdate());


insert into tbl_especialidades (id, especialidad)
values (null, 'Alergología'),
       (null, 'Anestesiología'),
       (null, 'Cardiología'),
       (null, 'Gastroenterología'),
       (null, 'Endocrinología'),
       (null, 'Epidemiología'),
       (null, 'Geriatría'),
       (null, 'Hematología'),
       (null, 'Infectología'),
       (null, 'Medicina aeroespacial'),
       (null, 'Medicina del deporte'),
       (null, 'Medicina del trabajo'),
       (null, 'Medicina de urgencias'),
       (null, 'Medicina familiar y comunitaria'),
       (null, 'Medicina física y rehabilitación'),
       (null, 'Medicina intensiva'),
       (null, 'Medicina interna'),
       (null, 'Medicina forense'),
       (null, 'Medicina preventiva y salud pública'),
       (null, 'Nefrología'),
       (null, 'Neumología'),
       (null, 'Neurología'),
       (null, 'Nutriología'),
       (null, 'Oncología médica'),
       (null, 'Oncología radioterápica'),
       (null, 'Pediatría'),
       (null, 'Psiquiatría'),
       (null, 'Reumatología'),
       (null, 'Toxicología'),
       (null, 'Cirugía cardíaca'),
       (null, 'Cirugía general'),
       (null, 'Cirugía oral y maxilofacial'),
       (null, 'Cirugía ortopédica'),
       (null, 'Cirugía pediátrica'),
       (null, 'Cirugía plástica'),
       (null, 'Cirugía torácica'),
       (null, 'Neurocirugía'),
       (null, 'Angiología'),
       (null, 'Dermatología'),
       (null, 'Ginecología y obstetricia o tocología'),
       (null, 'Oftalmología'),
       (null, 'Otorrinolaringología'),
       (null, 'Urología'),
       (null, 'Traumatología'),
       (null, 'Análisis clínico'),
       (null, 'Anatomía patológica'),
       (null, 'Bioquímica clínica'),
       (null, 'Farmacología'),
       (null, 'Genética médica'),
       (null, 'Inmunología'),
       (null, 'Medicina nuclear'),
       (null, 'Microbiología y parasitología'),
       (null, 'Neurofisiología clínica'),
       (null, 'Radiología');

insert into tbl_tipos_prescripciones (id, tipo_prescripcion)
values (null, 'Receta Retenida'),
       (null, 'Receta cheque');

insert into tbl_farmacos (id, nombre_farmaco, id_tipo_prescripcion)
values (null, 'Amitriptilina + Clordiazepóxido', 1),
       (null, 'Bromazepam', 1),
       (null, 'Brotizolam', 1),
       (null, 'Butorfanol', 1),
       (null, 'Clobazam', 1),
       (null, 'Clonazepam', 1),
       (null, 'Clorazepato dipotásico', 1),
       (null, 'Cloxazolam', 1),
       (null, 'Codeína + Paracetamol', 1),
       (null, 'Diazepam', 1),
       (null, 'Isotretinoína', 1),
       (null, 'Ketazolam', 1),
       (null, 'Loprazolam', 1),
       (null, 'Lorazepam', 1),
       (null, 'Midazolam', 1),
       (null, 'Oxazepam', 1),
       (null, 'Pemolina', 1),
       (null, 'Prazepam', 1),
       (null, 'Tetrazepam', 1),
       (null, 'Triazolam', 1),
       (null, 'Catina', 2),
       (null, 'Dietilpropión', 2),
       (null, 'Femproporex', 2),
       (null, 'Fenetilina', 2),
       (null, 'Fenobarbital', 2),
       (null, 'Fentermina', 2),
       (null, 'Flunitrazepam', 2),
       (null, 'Mazindol', 2),
       (null, 'Meperidina', 2),
       (null, 'Metadona', 2),
       (null, 'Metilfenidato', 2),
       (null, 'Morfina clorhidrato', 2),
       (null, 'Morfina sulfato', 2),
       (null, 'Oxicodona', 2),
       (null, 'Petidina', 2),
       (null, 'Alobarbital', 2),
       (null, 'Amobarbital', 2),
       (null, 'Aprobarbital', 2),
       (null, 'Barbital', 2),
       (null, 'Brallobarbital', 2),
       (null, 'Fenobarbital', 2),
       (null, 'Hexobarbital', 2),
       (null, 'Mefobarbital', 2),
       (null, 'Meprobamato', 2),
       (null, 'Pentobarbital', 2),
       (null, 'Proxibarbal', 2),
       (null, 'Secbutabarbital', 2),
       (null, 'Secobarbital', 2);

insert into tbl_miligramos (id, miligramo, id_farmaco)
values (null, 500, 1),
       (null, 500, 2),
       (null, 25, 3),
       (null, 50, 4),
       (null, 100, 5),
       (null, 100, 6),
       (null, 5, 7),
       (null, 8, 7),
       (null, 8, 8),
       (null, 5, 8),
       (null, 50, 9),
       (null, 500, 9),
       (null, 5, 9),
       (null, 25, 10),
       (null, 100, 10),
       (null, 50, 10),
       (null, 5, 11),
       (null, 50, 11),
       (null, 25, 11),
       (null, 500, 12),
       (null, 5, 13),
       (null, 50, 14),
       (null, 500, 14),
       (null, 25, 14),
       (null, 25, 15),
       (null, 25, 16),
       (null, 50, 16),
       (null, 100, 16),
       (null, 50, 17),
       (null, 500, 18),
       (null, 500, 19),
       (null, 50, 20),
       (null, 500, 21),
       (null, 100, 22),
       (null, 100, 23),
       (null, 10, 24),
       (null, 100, 25),
       (null, 25, 25),
       (null, 50, 25),
       (null, 500, 26),
       (null, 5, 27),
       (null, 10, 28),
       (null, 100, 29),
       (null, 500, 30),
       (null, 50, 31),
       (null, 5, 32),
       (null, 25, 33),
       (null, 8, 33),
       (null, 8, 34),
       (null, 100, 35),
       (null, 5, 35),
       (null, 5, 36),
       (null, 25, 37),
       (null, 500, 38),
       (null, 500, 39),
       (null, 500, 40),
       (null, 500, 41),
       (null, 50, 42),
       (null, 25, 43),
       (null, 5, 44),
       (null, 5, 45),
       (null, 8, 46),
       (null, 500, 47),
       (null, 50, 48);

insert into tbl_estado_prescripcion (id, estado)
values (null, 'vigente'),
       (null, 'no utilizada'),
       (null, 'usada'),
       (null, 'fin tratamiento');
